export const portfolioData = {
  name: "Minh Truong",
  displayName: "truongminhdev",
  title: "Frontend Developer",
  bio: "A passionate frontend developer and Year 4 IT student at Hutech University. Building responsive web applications and exploring modern technologies. I love creating clean, user-friendly interfaces with React, TypeScript, and Next.js.",
  shortBio: "Frontend dev focused on React, TypeScript, and modern web technologies.",
  email: "truongminh0949@gmail.com",
  github: "https://github.com/minhe51805",
  facebook: "https://www.facebook.com/profile.php?id=100083981328770",
  cvUrl: "/asset/Truong-Duong-Bao-Minh-TopCV.vn-010924.174113.pdf",
  location: "Ho Chi Minh City, Vietnam",
  education: {
    school: "Hutech University",
    degree: "Information Technology",
  },
  experience: "Frontend Developer",
  githubStats: {
    repos: 24,
    followers: 7,
    following: 8,
    stars: 139,
  },
  skills: {
    frontend: [
      { name: "React", level: "Experienced" },
      { name: "Next.js", level: "Experienced" },
      { name: "TypeScript", level: "Experienced" },
      { name: "Tailwind CSS", level: "Experienced" },
      { name: "HTML/CSS", level: "Experienced" },
      { name: "JavaScript", level: "Experienced" },
      { name: "Material UI", level: "Intermediate" },
      { name: "SASS/SCSS", level: "Intermediate" },
    ],
    backend: [
      { name: "FastAPI", level: "Intermediate" },
      { name: "Node.js", level: "Intermediate" },
      { name: "PostgreSQL", level: "Intermediate" },
      { name: "Python", level: "Intermediate" },
      { name: "Rust", level: "Basic" },
      { name: "Git", level: "Experienced" },
    ],
  },
  projects: [
    {
      name: "UrbanReflex",
      description:
        "Open-source smart city platform bridging urban data into NGSI-LD ecosystem with real-time monitoring, air quality sensors, and citizen reporting. 132 GitHub stars.",
      tags: ["Next.js", "FastAPI", "AI", "Smart City", "NGSI-LD"],
      githubUrl: "https://github.com/minhe51805/UrbanReflex",
      demoUrl: "https://minhe51805.github.io/UrbanReflex/",
      imageUrl: "/img/project-urbanreflex.svg",
      stars: 132,
      language: "TypeScript",
    },
    {
      name: "EduPath",
      description:
        "AI-first study abroad counseling platform built at LotusHack 2026. Transparent, data-grounded AI counselor for consulting centers and students.",
      tags: ["Next.js", "AI", "TypeScript", "Vercel"],
      githubUrl: "https://github.com/minhe51805/LotusHack-2026",
      demoUrl: "https://lotushacks2026.devpost.com/",
      imageUrl: "/img/project-lotushack.svg",
      stars: 0,
      language: "TypeScript",
    },
    {
      name: "TabLer",
      description:
        "Fast, modern cross-platform database client for developers. Supports PostgreSQL, MySQL, MongoDB, SQLite, and MSSQL.",
      tags: ["Tauri", "React", "Rust", "TypeScript"],
      githubUrl: "https://github.com/minhe51805/Tabler",
      demoUrl: "https://github.com/minhe51805/Tabler",
      imageUrl: "/img/project-tabler.svg",
      stars: 4,
      language: "TypeScript",
    },
    {
      name: "GAIA Platform",
      description:
        "IoT-AI-Blockchain platform for Vietnamese agriculture. Real-time environmental data, AI analysis, and blockchain transparency.",
      tags: ["IoT", "AI", "Blockchain", "Python"],
      githubUrl: "https://github.com/minhe51805/Pione_AIBlockchainIoT-WAGTeam",
      demoUrl: "https://163-61-183-90.nip.io/",
      imageUrl: "/img/project-gaia.svg",
      stars: 2,
      language: "Python",
    },
    {
      name: "Mamothon",
      description:
        "24-hour hackathon challenge platform with real-time tracking, team collaboration, and submission management.",
      tags: ["Next.js", "TypeScript", "Vercel"],
      githubUrl: "https://github.com/minhe51805/mamothon",
      demoUrl: "https://mamothon.vercel.app",
      imageUrl: "/img/project-mamothon.svg",
      stars: 0,
      language: "TypeScript",
    },
    {
      name: "Web SmartSwitch",
      description:
        "Web-based smart switch control system with IoT integration. Remote device management and automation.",
      tags: ["JavaScript", "IoT", "Web"],
      githubUrl: "https://github.com/minhe51805/Web_SmartSwitch_BangD",
      demoUrl: "https://github.com/minhe51805/Web_SmartSwitch_BangD",
      imageUrl: "/img/project-smartswitch.svg",
      stars: 1,
      language: "JavaScript",
    },
  ],
  profileImage: "/img/Asset 1@4x-8.png",
  aboutImage: "/img/About-picture.png",
};
